### PR TITLE
Closes #14

### LINKED ISSUE #14: Go GC is not happy
Using ```go1.5.1```

```
runtime:objectstart Span weird: p=0xc8206a6000 k=0x6410353 s.start=0xc8206a6000 s.limit=0xc8205c0000 s.state=2
fatal error: objectstart: bad pointer in unexpected span

goroutine 8 [running]:
runtime.throw(0x6c9b20, 0x2b)
	/usr/local/go/src/runtime/panic.go:527 +0x90 fp=0xc820030e18 sp=0xc820030e00
runtime.heapBitsForObject(0xc8206a6000, 0x0, 0x0, 0xc800000000, 0x7f1e1595fe30)
	/usr/local/go/src/runtime/mbitmap.go:217 +0x287 fp=0xc820030e50 sp=0xc820030e18
runtime.scanobject(0xc8205ae000, 0xc820025c20)
	/usr/local/go/src/runtime/mgcmark.go:878 +0x239 fp=0xc820030f20 sp=0xc820030e50
runtime.gcDrain(0xc820025c20, 0x7d0)
	/usr/local/go/src/runtime/mgcmark.go:689 +0xf4 fp=0xc820030f50 sp=0xc820030f20
runtime.gcBgMarkWorker(0xc820024a00)
	/usr/local/go/src/runtime/mgc.go:1320 +0x281 fp=0xc820030fb8 sp=0xc820030f50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820030fc0 sp=0xc820030fb8
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1239 +0x93

goroutine 1 [chan receive]:
testing.RunTests(0x6de8a8, 0x97daa0, 0x3, 0x3, 0xc820053e01)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc820045f08, 0xc820073520)
	/usr/local/go/src/testing/testing.go:494 +0x70
main.main()
	_/home/rawr/Projects/compress/internal/benchmark/_test/_testmain.go:58 +0x116

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [runnable, locked to thread]:
gopkg.in/kothar/brotli-go.v0/dec._Cfunc_BrotliDecompressStream(0xc8205afb10, 0xc8205afb18, 0xc8205a4000, 0xc8205a6000, 0xc8205afb20, 0xc8205ae000, 0x2)
	??:0 +0x39
gopkg.in/kothar/brotli-go.v0/dec.(*BrotliReader).Read(0xc8205ae000, 0xc82022c000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/home/rawr/.go/src/gopkg.in/kothar/brotli-go.v0/dec/decode.go:122 +0x38e
io.copyBuffer(0x7f1e13d379b0, 0xc82057e100, 0x7f1e13d379d8, 0xc8205ae000, 0xc82022c000, 0x8000, 0x8000, 0x10000, 0x0, 0x0)
	/usr/local/go/src/io/io.go:381 +0x247
io.Copy(0x7f1e13d379b0, 0xc82057e100, 0x7f1e13d379d8, 0xc8205ae000, 0xc8205ae000, 0x0, 0x0)
	/usr/local/go/src/io/io.go:351 +0x64
_/home/rawr/Projects/compress/internal/benchmark.testRoundTrip(0xc82009c120, 0x6de6e8, 0x6de6f0)
	/home/rawr/Projects/compress/internal/benchmark/common_test.go:47 +0x102e
_/home/rawr/Projects/compress/internal/benchmark.TestCGoRoundTripBrotli(0xc82009c120)
	/home/rawr/Projects/compress/internal/benchmark/cgo_brotlib_test.go:12 +0x117
testing.tRunner(0xc82009c120, 0x97daa0)
	/usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:561 +0x86d
exit status 2
FAIL	_/home/rawr/Projects/compress/internal/benchmark	0.094s
```

I actually struggled with a very similar problem when I was wrapping zlib.
You might want to take a look at what [cgzip did to make their cgo stuff happy with go1.5](https://github.com/youtube/vitess/commit/071d0e649f22034ad4285c7431ac0a2c9c20090d#diff-61a5b337943f83de2390afaddf93fb45). [Specifically the comment here](https://github.com/youtube/vitess/blob/master/go/cgzip/zstream.go#L86-L89).

### PR DESCRIPTION
**Pull request by fasterthanlime**

### CODE REVIEW

File: dec/decode.go [hunk 1]
```diff
@@ -122,7 +127,7 @@ func (r *BrotliReader) Read(p []byte) (cnt int, err error) {
 				&availableOut,
 				&nextOut,
 				&r.totalOut,
-				r.state,
+				(*C.BrotliState)(unsafe.Pointer(&r.state[0])),
```
Comment (fasterthanlime) [inline dec/decode.go]: this cast might be overly long-winded, I have no idea what a typical gopher would write

Comment (kothar) [inline dec/decode.go]: :+1: I can't see any other way of handling it. I think unsafe pointers are intentionally long winded to use
